name: 云盘签到

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '45 10 * * *'
  workflow_dispatch:
  watch:
    types: started
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 打印ip地址
        run: echo "ip地址是 $(curl -s ifconfig.me)"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 安装环境
        run: pip install -r requirements.txt
      - name: 签到
        run: |
          (echo "签到时间 $(date "+%F %T") [![签到状态](https://github.com/jakobheng/189pan-checkin1/actions/workflows/main.yml/badge.svg?branch=main)](https://github.com/jakobheng/189pan-checkin1/actions/workflows/main.yml)" && python3 ./main.py) | tee >(sed 's/^/- /' > index.md)
        env:
          TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
          TYYP_PSW: ${{ secrets.TYYP_PSW }}
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

